# Generated by Django 4.0.4 on 2022-06-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEATS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=1)),
                ('num', models.CharField(max_length=2)),
                ('transactionId', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TRANSACTION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
