# Generated by Django 4.0.4 on 2022-06-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_transaction_email_transaction_name_transaction_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SEATS',
            new_name='Event1_seats',
        ),
    ]
