# Generated by Django 4.0.4 on 2022-06-04 11:24

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_event1_seats_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='seat',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default=['aff', 'faasfasf'], max_length=180, size=4),
            preserve_default=False,
        ),
    ]
